apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapp
  labels:
    app: tasksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapp
  template:
    metadata:
      labels:
        app: tasksapp
    spec:
      containers:
        - name: tasksapp
          image: reisafriche/test:1.0.3
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tasksapp-service
spec:
  type: NodePort
  selector:
    app: tasksapp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000