apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployment", "configmaps"]
    verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: developer-binding
subjects:
  - kind: User
    name: fan
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: yuna
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io