apiVersion: apps/v1
kind: Deployment
metadata:
  name: outlets-v2
  labels:
    app: outlets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outlets
      version: 0.2.0
  template:
    metadata:
      labels:
        app: outlets
        version: 0.2.0
    spec:
      containers:
        - name: outlets
          image: reisafriche/vue-app:v5-domain
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: 0.2.0
---
apiVersion: v1
kind: Service
metadata:
  name: outlets
spec:
  # type: NodePort
  selector:
    app: outlets-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: {{.Values.webapp.nodePort}}
  type: LoadBalancer