apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.api.name}}
  labels:
    app: {{.Values.api.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.api.name}}
  template:
    metadata:
      labels:
        app: {{.Values.api.name}}
    spec:
      containers:
        - name: {{.Values.api.name}}
          image: "{{.Values.apiImage.repository}}:{{.Values.apiImage.tag}}"
          ports:
          - containerPort: {{.Values.api.port}}
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: USER_PWD
            valueFrom:
              secretKeyRef: 
                name: mongo-secret
                key: mongo-pwd
          - name: DB_URL
            valueFrom:
              configMapKeyRef: 
                name: mongo-config
                key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.api.svcName}}
spec:
  # type: NodePort
  selector:
    app: {{.Values.api.name}}
  ports:
    - protocol: TCP
      port: {{.Values.api.port}}
      targetPort: {{.Values.api.port}}
      # nodePort: {{.Values.api.nodePort}}
  type: LoadBalancer