apiVersion: apps/v1
kind: Stateful
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  serviceName: ""
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:{{.Values.mongodb.version}}
        ports:
        - containerPort: {{.Values.mongodb.port}}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-pwd
        volumeMounts:
            - name: storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongodb.svcName}}
spec:
  selector:
    app: mongo
  ports:
    - port: {{.Values.mongodb.port}}
      name: web
  ClusterIP: None

---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongo-pv
#spec:
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /tmp/db
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi