apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{.Values.api.name}}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - {}
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: mongo