apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: pod-viewer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: pod-viewer-binding
subjects:
  - kind: User
    name: fan
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: yuna
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: cai
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io