apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  namespace: default
  name: secret-viewer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: secret-viewer-binding
subjects:
  - kind: User
    name: fan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-viewer
  apiGroup: rbac.authorization.k8s.io