apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: {{.Release.Version}}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{.Release.Version}}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{.Values.webImage.repository}}:{{.Values.webImage.tag}}"
          ports:
            - containerPort: {{.Values.webapp.port}}
          env:
            - name: VERSION
              value: {{.Release.Version}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.webapp.svcName}}
spec:
  # type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{.Values.webapp.port}}
      targetPort: {{.Values.webapp.port}}
      # nodePort: {{.Values.webapp.nodePort}}
  type: LoadBalancer